=== JoanIticbcn/M4/JSON_XML_DTD/botiga.dtd
<!ELEMENT botiga (Videojocs , clients )>
<!ELEMENT Videojocs (plataforma)>
<!ELEMENT plataforma (pc*,ps5*)>
<!ELEMENT pc (videojoc*)>
<!ELEMENT ps5 (videojoc*)>
<!ELEMENT videojoc (titol,companyia+,categoria+,preu,data_llançament)>
<!ELEMENT titol  (#PCDATA)>
<!ELEMENT companyia (#PCDATA)>
<!ELEMENT categoria  (#PCDATA)>
<!ELEMENT preu (#PCDATA)>
<!ELEMENT data_llançament (#PCDATA)>
<!ELEMENT clients (client*)>
<!ELEMENT client (nom,telefon+,email?,data_neixament,compres,adreça*)>
<!ELEMENT nom (#PCDATA)>
<!ELEMENT telefon (#PCDATA)>
<!ELEMENT email (#PCDATA)>
<!ELEMENT data_neixament (#PCDATA)>
<!ELEMENT compres (si | no )>
<!ELEMENT si EMPTY>
<!ELEMENT no EMPTY>
<!ELEMENT adreça (localitat*)>
<!ELEMENT localitat ( codi_postal+, carrer+)>
<!ELEMENT codi_postal  (#PCDATA)>
<!ELEMENT carrer (nom_carrer,num_portal)>
<!ELEMENT nom_carrer (#PCDATA)>
<!ELEMENT num_portal (#PCDATA)>
<!ATTLIST videojoc id ID #REQUIRED>
<!ATTLIST client id ID #REQUIRED>
<!ATTLIST compres id_jocs IDREFS #REQUIRED>
<!ATTLIST telefon pais CDATA #REQUIRED>

=== JoanIticbcn/M4/JSON_XML_DTD/gamecat.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE botiga SYSTEM "botiga.dtd">
<botiga>
<Videojocs>
    <plataforma>
        <pc>
            <videojoc id="XXXA">
                <titol>Battlefield 2047</titol>
                <companyia>EA Sports</companyia>
                <categoria>Shooter</categoria>
                <preu>40€</preu>
                <data_llançament>10/07/2021</data_llançament>
            </videojoc>
            <videojoc id="XXXB">
                <titol>Grand Theft Auto 5</titol>
                <companyia>Rockstar</companyia>
                <categoria>Shooter</categoria>
                <preu>40€</preu>
                <data_llançament>17/09/13</data_llançament>
            </videojoc>
        </pc>
        <ps5>
            <videojoc id="XXXC">
                <titol>Fornite</titol>
                <companyia>Epic Games</companyia>
                <categoria>BattleRoyale</categoria>
          <preu>Gratis</preu>
                <data_llançament> 25/07/2017</data_llançament> 
            </videojoc>
        </ps5>
    </plataforma>
</Videojocs>




<clients>
  <client id="YYYA">
    <nom>PERE </nom>
    <telefon pais="España"> 634124459</telefon>
    <email>perepere@gmail.com</email>
    <data_neixament>1900</data_neixament>
    <compres id_jocs="XXXC XXXA"><si></si></compres>
    <adreça>
        <localitat>
            <codi_postal>08005</codi_postal>
            <carrer>
                <nom_carrer>carrer itic</nom_carrer>
                <num_portal>2</num_portal>
            </carrer>
        </localitat>
    </adreça>
</client>
</clients>
</botiga>
