=== JoanIticbcn/M4/JSON_XML_DTD/pracicaPerexamen.dtd
<!-- DTD para proyectos de diseÃ±o web -->
<!ELEMENT proyectos (proyecto+)>

<!ELEMENT proyecto (nombre, cliente, disenadores, tecnologias, fecha_finalizacion)>
<!ATTLIST proyecto id ID #REQUIRED>
<!ATTLIST proyecto idioma (cat | es) "cat">

<!ELEMENT nombre (#PCDATA)>
<!ELEMENT cliente (nombre, contacto?)>
<!ELEMENT disenadores (disenador*)>
<!ELEMENT tecnologias (tecnologia+)>
<!ELEMENT fecha_finalizacion (#PCDATA)>

<!ELEMENT disenador (nombre,  contacto?)>
<!ELEMENT tecnologia (#PCDATA)>

<!ELEMENT contacto (correo?, telefono?)>
<!ELEMENT correo (#PCDATA)>
<!ELEMENT telefono (#PCDATA)>
<!ATTLIST telefono pais (es | fr | br | pt) #REQUIRED>

=== JoanIticbcn/M4/JSON_XML_DTD/practicaPerexamen2.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE proyectos SYSTEM "./pracicaPerexamen.dtd">
<proyectos>
    <proyecto id="AAA">
        <nombre>Raid area51</nombre>
        <cliente>
            <nombre>Elon musk</nombre>
        </cliente>
        <disenadores>

        </disenadores>
        <tecnologias>
            <tecnologia>HTML</tecnologia>
        </tecnologias>
        <fecha_finalizacion>12/12/2052</fecha_finalizacion>

    </proyecto>
</proyectos>

=== JoanIticbcn/M4/JSON_XML_DTD/practicaPerExamen.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE proyectos SYSTEM "./pracicaPerexamen.dtd">
<proyectos>
    <proyecto id="AAA" idioma="cat">
        <nombre>Raid area51</nombre>
        <cliente>
            <nombre>Elon musk</nombre>
            <contacto>
                <correo>elon@yahho.com</correo>
                <telefono pais="es">+42 123 912 239 32</telefono>
            </contacto>
        </cliente>
        <disenadores>
            <disenador>
                <nombre>Elon musk</nombre>
                <contacto>
                    <correo>elon@yahho.com</correo>
                    <telefono pais="es">+42 123 912 239 32</telefono>
                </contacto>
            </disenador>
        </disenadores>
        <tecnologias>
            <tecnologia>Linux</tecnologia>
            <tecnologia>HTML</tecnologia>
        </tecnologias>
        <fecha_finalizacion>12/12/2052</fecha_finalizacion>

    </proyecto>
</proyectos>
